// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grSimMessage.proto

#ifndef PROTOBUF_grSimMessage_2eproto__INCLUDED
#define PROTOBUF_grSimMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace grSimMessage {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_grSimMessage_2eproto();
void protobuf_AssignDesc_grSimMessage_2eproto();
void protobuf_ShutdownFile_grSimMessage_2eproto();

class grSimInfo;

// ===================================================================

class grSimInfo : public ::google::protobuf::Message {
 public:
  grSimInfo();
  virtual ~grSimInfo();

  grSimInfo(const grSimInfo& from);

  inline grSimInfo& operator=(const grSimInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const grSimInfo& default_instance();

  void Swap(grSimInfo* other);

  // implements Message ----------------------------------------------

  grSimInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const grSimInfo& from);
  void MergeFrom(const grSimInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // optional bool isInfrared = 2;
  inline bool has_isinfrared() const;
  inline void clear_isinfrared();
  static const int kIsInfraredFieldNumber = 2;
  inline bool isinfrared() const;
  inline void set_isinfrared(bool value);

  // @@protoc_insertion_point(class_scope:grSimMessage.grSimInfo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_isinfrared();
  inline void clear_has_isinfrared();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 id_;
  bool isinfrared_;
  friend void  protobuf_AddDesc_grSimMessage_2eproto();
  friend void protobuf_AssignDesc_grSimMessage_2eproto();
  friend void protobuf_ShutdownFile_grSimMessage_2eproto();

  void InitAsDefaultInstance();
  static grSimInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// grSimInfo

// required uint32 id = 1;
inline bool grSimInfo::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void grSimInfo::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void grSimInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void grSimInfo::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 grSimInfo::id() const {
  // @@protoc_insertion_point(field_get:grSimMessage.grSimInfo.id)
  return id_;
}
inline void grSimInfo::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:grSimMessage.grSimInfo.id)
}

// optional bool isInfrared = 2;
inline bool grSimInfo::has_isinfrared() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void grSimInfo::set_has_isinfrared() {
  _has_bits_[0] |= 0x00000002u;
}
inline void grSimInfo::clear_has_isinfrared() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void grSimInfo::clear_isinfrared() {
  isinfrared_ = false;
  clear_has_isinfrared();
}
inline bool grSimInfo::isinfrared() const {
  // @@protoc_insertion_point(field_get:grSimMessage.grSimInfo.isInfrared)
  return isinfrared_;
}
inline void grSimInfo::set_isinfrared(bool value) {
  set_has_isinfrared();
  isinfrared_ = value;
  // @@protoc_insertion_point(field_set:grSimMessage.grSimInfo.isInfrared)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace grSimMessage

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_grSimMessage_2eproto__INCLUDED
